NUMBER_OF_WANS = 3

NUMBER_OF_NODES_WAN0 = 10
NUMBER_OF_SATELLITES_WAN0 = 2
TOTAL_WAN0 = NUMBER_OF_NODES_WAN0 + NUMBER_OF_SATELLITES_WAN0

NUMBER_OF_NODES_WAN1 = 10
NUMBER_OF_SATELLITES_WAN1 =2
TOTAL_WAN1 = NUMBER_OF_NODES_WAN1 + NUMBER_OF_SATELLITES_WAN1

NUMBER_OF_NODES_WAN2 = 10
NUMBER_OF_SATELLITES_WAN2 = 2
TOTAL_WAN2 = NUMBER_OF_NODES_WAN2 + NUMBER_OF_SATELLITES_WAN2

TOTAL_NODES = [TOTAL_WAN0, TOTAL_WAN1, TOTAL_WAN2]
