# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialo_creater(object):
    def setupUi(self, Dialo_creater):
        Dialo_creater.setObjectName("Dialo_creater")
        Dialo_creater.resize(364, 676)
        self.gridLayout_7 = QtWidgets.QGridLayout(Dialo_creater)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(Dialo_creater)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_wan0 = QtWidgets.QWidget()
        self.tab_wan0.setObjectName("tab_wan0")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_wan0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_wan0)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.sb_nodes_wan0 = QtWidgets.QSpinBox(self.tab_wan0)
        self.sb_nodes_wan0.setMinimum(10)
        self.sb_nodes_wan0.setMaximum(15)
        self.sb_nodes_wan0.setObjectName("sb_nodes_wan0")
        self.horizontalLayout.addWidget(self.sb_nodes_wan0)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableWidget_nodes_wan0 = QtWidgets.QTableWidget(self.tab_wan0)
        self.tableWidget_nodes_wan0.setRowCount(10)
        self.tableWidget_nodes_wan0.setColumnCount(1)
        self.tableWidget_nodes_wan0.setObjectName("tableWidget_nodes_wan0")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nodes_wan0.setHorizontalHeaderItem(0, item)
        self.tableWidget_nodes_wan0.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget_nodes_wan0.horizontalHeader().setHighlightSections(False)
        self.tableWidget_nodes_wan0.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_nodes_wan0.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_nodes_wan0.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_nodes_wan0.verticalHeader().setVisible(True)
        self.tableWidget_nodes_wan0.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_nodes_wan0.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_nodes_wan0.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_nodes_wan0.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget_nodes_wan0, 1, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab_wan0)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_topology_0 = QtWidgets.QComboBox(self.tab_wan0)
        self.comboBox_topology_0.setObjectName("comboBox_topology_0")
        self.comboBox_topology_0.addItem("")
        self.comboBox_topology_0.addItem("")
        self.comboBox_topology_0.addItem("")
        self.comboBox_topology_0.addItem("")
        self.verticalLayout.addWidget(self.comboBox_topology_0)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_wan0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.sb_satellite_wan0 = QtWidgets.QSpinBox(self.tab_wan0)
        self.sb_satellite_wan0.setMinimum(2)
        self.sb_satellite_wan0.setMaximum(5)
        self.sb_satellite_wan0.setObjectName("sb_satellite_wan0")
        self.horizontalLayout_2.addWidget(self.sb_satellite_wan0)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.tableWidget_satellites_wan0 = QtWidgets.QTableWidget(self.tab_wan0)
        self.tableWidget_satellites_wan0.setRowCount(2)
        self.tableWidget_satellites_wan0.setColumnCount(2)
        self.tableWidget_satellites_wan0.setObjectName("tableWidget_satellites_wan0")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_satellites_wan0.setHorizontalHeaderItem(0, item)
        self.tableWidget_satellites_wan0.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget_satellites_wan0.horizontalHeader().setHighlightSections(False)
        self.tableWidget_satellites_wan0.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_satellites_wan0.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_satellites_wan0.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_satellites_wan0.verticalHeader().setVisible(True)
        self.tableWidget_satellites_wan0.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_satellites_wan0.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_satellites_wan0.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_satellites_wan0.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.tableWidget_satellites_wan0)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.gridLayout_4.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_wan0, "")
        self.tab_wan1 = QtWidgets.QWidget()
        self.tab_wan1.setObjectName("tab_wan1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_wan1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.tab_wan1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.sb_nodes_wan1 = QtWidgets.QSpinBox(self.tab_wan1)
        self.sb_nodes_wan1.setMinimum(10)
        self.sb_nodes_wan1.setMaximum(15)
        self.sb_nodes_wan1.setObjectName("sb_nodes_wan1")
        self.horizontalLayout_3.addWidget(self.sb_nodes_wan1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.tableWidget_nodes_wan1 = QtWidgets.QTableWidget(self.tab_wan1)
        self.tableWidget_nodes_wan1.setRowCount(10)
        self.tableWidget_nodes_wan1.setColumnCount(1)
        self.tableWidget_nodes_wan1.setObjectName("tableWidget_nodes_wan1")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nodes_wan1.setHorizontalHeaderItem(0, item)
        self.tableWidget_nodes_wan1.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget_nodes_wan1.horizontalHeader().setHighlightSections(False)
        self.tableWidget_nodes_wan1.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_nodes_wan1.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_nodes_wan1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_nodes_wan1.verticalHeader().setVisible(False)
        self.tableWidget_nodes_wan1.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_nodes_wan1.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_nodes_wan1.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_nodes_wan1.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget_nodes_wan1, 1, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_wan1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.comboBox_topology_1 = QtWidgets.QComboBox(self.tab_wan1)
        self.comboBox_topology_1.setObjectName("comboBox_topology_1")
        self.comboBox_topology_1.addItem("")
        self.comboBox_topology_1.addItem("")
        self.comboBox_topology_1.addItem("")
        self.comboBox_topology_1.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_topology_1)
        self.verticalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.tab_wan1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.sb_satellite_wan1 = QtWidgets.QSpinBox(self.tab_wan1)
        self.sb_satellite_wan1.setMinimum(2)
        self.sb_satellite_wan1.setMaximum(5)
        self.sb_satellite_wan1.setObjectName("sb_satellite_wan1")
        self.horizontalLayout_4.addWidget(self.sb_satellite_wan1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.tableWidget_satellites_wan1 = QtWidgets.QTableWidget(self.tab_wan1)
        self.tableWidget_satellites_wan1.setRowCount(2)
        self.tableWidget_satellites_wan1.setColumnCount(1)
        self.tableWidget_satellites_wan1.setObjectName("tableWidget_satellites_wan1")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_satellites_wan1.setHorizontalHeaderItem(0, item)
        self.tableWidget_satellites_wan1.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget_satellites_wan1.horizontalHeader().setHighlightSections(False)
        self.tableWidget_satellites_wan1.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_satellites_wan1.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_satellites_wan1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_satellites_wan1.verticalHeader().setVisible(False)
        self.tableWidget_satellites_wan1.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_satellites_wan1.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_satellites_wan1.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_satellites_wan1.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.tableWidget_satellites_wan1)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.gridLayout_5.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_wan1, "")
        self.tab_wan2 = QtWidgets.QWidget()
        self.tab_wan2.setObjectName("tab_wan2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_wan2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.tab_wan2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.sb_nodes_wan2 = QtWidgets.QSpinBox(self.tab_wan2)
        self.sb_nodes_wan2.setMinimum(10)
        self.sb_nodes_wan2.setMaximum(15)
        self.sb_nodes_wan2.setObjectName("sb_nodes_wan2")
        self.horizontalLayout_5.addWidget(self.sb_nodes_wan2)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tableWidget_nodes_wan2 = QtWidgets.QTableWidget(self.tab_wan2)
        self.tableWidget_nodes_wan2.setRowCount(10)
        self.tableWidget_nodes_wan2.setColumnCount(1)
        self.tableWidget_nodes_wan2.setObjectName("tableWidget_nodes_wan2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nodes_wan2.setHorizontalHeaderItem(0, item)
        self.tableWidget_nodes_wan2.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget_nodes_wan2.horizontalHeader().setHighlightSections(False)
        self.tableWidget_nodes_wan2.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_nodes_wan2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_nodes_wan2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_nodes_wan2.verticalHeader().setVisible(False)
        self.tableWidget_nodes_wan2.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_nodes_wan2.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_nodes_wan2.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_nodes_wan2.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidget_nodes_wan2, 1, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab_wan2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.comboBox_topology_2 = QtWidgets.QComboBox(self.tab_wan2)
        self.comboBox_topology_2.setObjectName("comboBox_topology_2")
        self.comboBox_topology_2.addItem("")
        self.comboBox_topology_2.addItem("")
        self.comboBox_topology_2.addItem("")
        self.comboBox_topology_2.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_topology_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_wan2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.sb_satellite_wan2 = QtWidgets.QSpinBox(self.tab_wan2)
        self.sb_satellite_wan2.setMinimum(2)
        self.sb_satellite_wan2.setMaximum(5)
        self.sb_satellite_wan2.setObjectName("sb_satellite_wan2")
        self.horizontalLayout_6.addWidget(self.sb_satellite_wan2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.tableWidget_satellites_wan2 = QtWidgets.QTableWidget(self.tab_wan2)
        self.tableWidget_satellites_wan2.setRowCount(2)
        self.tableWidget_satellites_wan2.setColumnCount(1)
        self.tableWidget_satellites_wan2.setObjectName("tableWidget_satellites_wan2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_satellites_wan2.setHorizontalHeaderItem(0, item)
        self.tableWidget_satellites_wan2.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget_satellites_wan2.horizontalHeader().setHighlightSections(False)
        self.tableWidget_satellites_wan2.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_satellites_wan2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_satellites_wan2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_satellites_wan2.verticalHeader().setVisible(False)
        self.tableWidget_satellites_wan2.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_satellites_wan2.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_satellites_wan2.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_satellites_wan2.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_9.addWidget(self.tableWidget_satellites_wan2)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_wan2, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialo_creater)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_7.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialo_creater)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialo_creater.accept)
        self.buttonBox.rejected.connect(Dialo_creater.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialo_creater)

    def retranslateUi(self, Dialo_creater):
        _translate = QtCore.QCoreApplication.translate
        Dialo_creater.setWindowTitle(_translate("Dialo_creater", "Dialog"))
        self.label_4.setText(_translate("Dialo_creater", "Nodes"))
        item = self.tableWidget_nodes_wan0.horizontalHeaderItem(0)
        item.setText(_translate("Dialo_creater", "Weight"))
        self.label.setText(_translate("Dialo_creater", "Network topology"))
        self.comboBox_topology_0.setItemText(0, _translate("Dialo_creater", "Ring"))
        self.comboBox_topology_0.setItemText(1, _translate("Dialo_creater", "Star"))
        self.comboBox_topology_0.setItemText(2, _translate("Dialo_creater", "Fully connected"))
        self.comboBox_topology_0.setItemText(3, _translate("Dialo_creater", "Line"))
        self.label_5.setText(_translate("Dialo_creater", "Satellites"))
        item = self.tableWidget_satellites_wan0.horizontalHeaderItem(0)
        item.setText(_translate("Dialo_creater", "Weight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wan0), _translate("Dialo_creater", "wan0"))
        self.label_6.setText(_translate("Dialo_creater", "Nodes"))
        item = self.tableWidget_nodes_wan1.horizontalHeaderItem(0)
        item.setText(_translate("Dialo_creater", "Weight"))
        self.label_2.setText(_translate("Dialo_creater", "Network topology"))
        self.comboBox_topology_1.setItemText(0, _translate("Dialo_creater", "Ring"))
        self.comboBox_topology_1.setItemText(1, _translate("Dialo_creater", "Star"))
        self.comboBox_topology_1.setItemText(2, _translate("Dialo_creater", "Fully connected"))
        self.comboBox_topology_1.setItemText(3, _translate("Dialo_creater", "Line"))
        self.label_7.setText(_translate("Dialo_creater", "Satellites"))
        item = self.tableWidget_satellites_wan1.horizontalHeaderItem(0)
        item.setText(_translate("Dialo_creater", "Weight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wan1), _translate("Dialo_creater", "wan1"))
        self.label_8.setText(_translate("Dialo_creater", "Nodes"))
        item = self.tableWidget_nodes_wan2.horizontalHeaderItem(0)
        item.setText(_translate("Dialo_creater", "Weight"))
        self.label_3.setText(_translate("Dialo_creater", "Network topology"))
        self.comboBox_topology_2.setItemText(0, _translate("Dialo_creater", "Ring"))
        self.comboBox_topology_2.setItemText(1, _translate("Dialo_creater", "Star"))
        self.comboBox_topology_2.setItemText(2, _translate("Dialo_creater", "Fully connected"))
        self.comboBox_topology_2.setItemText(3, _translate("Dialo_creater", "Line"))
        self.label_9.setText(_translate("Dialo_creater", "Satellites"))
        item = self.tableWidget_satellites_wan2.horizontalHeaderItem(0)
        item.setText(_translate("Dialo_creater", "Weight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wan2), _translate("Dialo_creater", "wan2"))

